Remora/Remora.Discord

- Backend/Remora.Discord.Gateway/Extensions/ServiceCollectionExtensions.cs
- Backend/Remora.Discord.Gateway/Extensions/TypeExtensions.cs
- Backend/Remora.Discord.Gateway/Services/ResponderService.cs
- Remora.Discord.sln
- Samples/LoadResolversFromAssembly/LoadResolversFromAssembly.csproj
- Samples/LoadResolversFromAssembly/Program.cs
- Samples/LoadResolversFromAssembly/Responders/EchoResponder.cs
- Tests/Remora.Discord.Gateway.Tests/Responders/MockedResponder.cs
- Tests/Remora.Discord.Gateway.Tests/Tests/TypeExtensionsTests.cs
The objective of this PR is to add a user friendly way to load all types implementing `IResponder<T>` in an assembly. With the current implementation, it is not possible to do that, since `ResponderService.RegisterResponder<TResponder>()` is not only internal but does not provide a non-generic overload.
> Add support to load all Responders in an Assembly.

- Remora.Discord.Commands/Responders/InteractionResponder.cs
Fixes an exception when using multiple options on a slash command. `SingleOrDefault` throws an exception when theres multiple options so the logic here was slightly wrong.
> Fix exception on multiple command options

- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
Long story short, `TaskCreationOptions.LongRunning` is for synchronous CPU-bound work, and this here is neither synchronous, nor CPU-bound.
Referring to the docs, this basically tells the thread pool to create an extra thread, to make up for the one that that this task is going to block for a long time.
```
Specifies that a task will be a long-running, coarse-grained operation involving fewer, larger components than fine-grained systems. It provides a hint to the TaskScheduler that oversubscription may be warranted. Oversubscription lets you create more threads than the available number of hardware threads. It also provides a hint to the task scheduler that an additional thread might be required for the task so that it does not block the forward progress of other threads or work items on …
```
> Fixed misuse of `TaskCreationOptions.LongRunning`

- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
Alternatively, make `IHello` an `internal` type, and expose the `HeartbeatLifetime` value on the gateway client itself.
> Fixed that IHello events are not dispatched to responders. Fixes #36

- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
- Tests/Remora.Discord.Gateway.Tests/Tests/DiscordGatewayClientTests.cs
- Tests/Remora.Discord.Gateway.Tests/Transport/Events/SendExceptionEvent.cs
- Tests/Remora.Discord.Gateway.Tests/Transport/MockedTransportSequenceBuilder.cs
- Tests/Remora.Discord.Gateway.Tests/Transport/MockedTransportService.cs
Fixed that the gateway client would not properly reconnect in the event of a network exception, due to improper management of cancellation tokens.
Resolves #39.
> Fixed gateway reconnection, in response to network exceptions.

- Tests/Remora.Discord.Commands.Tests/Extensions/CommandTreeExtensionTests.cs
Fixed a bug regarding nullability annotations, when running with the latest preview version of `Microsoft.CodeAnalysis.NetAnalyzers`.
Basically, putting a null-check-override on something once is no longer sufficient to eliminate null-checks down the line, when extensions are used. In truth, a null-check-override was never intended to carry down the line to future uses, but it appeared this way because Roslyn would incorrectly mark values that have the . operator applied to them as not possibly null, not realizing that extension methods make it possible to invoke the . operator upon null.
https://github.com/dotnet/roslyn/issues/48605
> Fixed a compilation error when running in VS 2019 Preview

- Backend/Remora.Discord.API.Abstractions/API/Gateway/IPayloadOfT.cs
- Backend/Remora.Discord.API/API/Payload.cs
- Backend/Remora.Discord.API/Json/Converters/Internal/PayloadConverter.cs
- Backend/Remora.Discord.Gateway/Responders/IResponder.cs
This eliminates the need for responders to allow for nullable data fields when the vast majority of them can never be null.
> Reworked `IPayload<T>` to not allow for null data fields

- Tests/Remora.Discord.API.Tests/Services/SampleBidirectionalDataSource.cs
- Tests/Remora.Discord.API.Tests/Services/SampleCommandDataSource.cs
- Tests/Remora.Discord.API.Tests/Services/SampleDataDescriptor.cs
- Tests/Remora.Discord.API.Tests/Services/SampleDataService.cs
- Tests/Remora.Discord.API.Tests/Services/SampleEventDataSource.cs
- Tests/Remora.Discord.API.Tests/Services/SampleObjectDataSource.cs
- Tests/Remora.Discord.API.Tests/TestBases/GatewayTestBase.cs
- Tests/Remora.Discord.API.Tests/TestBases/JsonBackedTypeTestBase.cs
Enhanced the JSON Sample Data testing system to display more meaingful test names, I.E. to have test names only include the relative path of the JSON file, not the full filesystem path, which would generally result in test names being truncated and unreadable within an IDE.
> JSON Sample Data Test Naming

- Backend/Remora.Discord.Rest/API/RestRequestBuilder.cs
Small change to remove the trailing question mark in query strings when there isn't actually a query. 
Unsure what the HTTP spec specifies in this case, but I don't feel it's semantically correct to leave it at the end when it's not being used.
> Remove trailing "?" when there are no query params

- Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IApplicationCommandOverwriteData.cs
- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestApplicationAPI.cs
- Backend/Remora.Discord.API/API/Objects/Interactions/ApplicationCommandOverwriteData.cs
- Backend/Remora.Discord.Rest/API/Applications/DiscordRestApplicationAPI.cs
- Remora.Discord.Commands/Services/SlashService.cs
- Tests/Remora.Discord.Rest.Tests/API/Applications/DiscordRestApplicationAPITests.cs
- Tests/Remora.Discord.Rest.Tests/Json/JsonObjectMatcherBuilder.cs
Enhanced the Rest Applications API to include the "default_permission" parameter when bulk overwriting commands, and to reduce verbosity.
> Enhanced bulk overwriting of slash command definitions

- Remora.Discord.Commands/Extensions/CommandTreeExtensions.cs
- Remora.Discord.Commands/Services/SlashService.cs
- Tests/Remora.Discord.Commands.Tests/Extensions/CommandTreeExtensionTests.cs
The translation now returns IBulkApplicationCommandData at the top level, rather than IApplicationCommandOption, to better reflect the Discord API model.
Other enhancements include consolidation of validation logic and error message generation, minor performance improvements in aggregate validations, such as counting and name-collision detection, and restructuring of private methods to properly leverage Result<T>, and eliminate null-check overrides.
> Reworked and enhanced the logic for translating Remora command trees into Discord command trees.

- Backend/Remora.Discord.Core/Optional.cs
- Tests/Remora.Discord.Tests/Tests/Core/Optional/OptionalTests.cs
So, hear me out. I encountered the need to write the following while building out logging infrastructure...
```cs
=> _userTracking.Invoke(
logger,
userId,
guildId,
username.HasValue
? username.Value.ToString()
: "Unspecified",
discriminator.HasValue
? discrimincator.Value.ToString()
: "Unspecified",
avatarHash.HasValue
? avatarHash.Value.ToString()
: "Unspecified",
nickname.HasValue
? nickname.Value.ToString()
: "Unspecified");
```
This is necessary because I can't reasonably configure all logger sinks to know how to serialize an `Optional<T>` value, especially those that attempt to JSON-serialize objects. Instead, they'll try and read from `.Value` and cause an exception in logging.
I'm usually a fan of not having debugging logic embedded in a type, so I generally like `DebuggerDisplay` …
> Enhanced Optional<T> to support meaningful stringification.

- Backend/Remora.Discord.API.Abstractions/API/Gateway/GatewayCloseStatus.cs
The value of GatewayCloseStatus.ShardingRequired is different from the document.
This PR will fix it.
document: https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-close-event-codes
> Fixed the value of ShardingRequired.

- Backend/Remora.Discord.API.Abstractions/API/Objects/Voice/IPartialVoiceState.cs
- Backend/Remora.Discord.API/API/Objects/Voice/PartialVoiceState.cs
IVoiceState has a RequestToSpeakTimestamp field, but IPartialVoiceState does not.
This PR will add the missing field.
> Fixed the missing field in IPartialVoiceState.

- Remora.Discord.Commands/Contexts/InteractionContext.cs
- Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs
- Remora.Discord.Commands/Remora.Discord.Commands.csproj.DotSettings
- Remora.Discord.Commands/Responders/CommandResponder.cs
- Remora.Discord.Commands/Responders/InteractionResponder.cs
- Remora.Discord.Commands/Services/Execution/ExecutionEventCollectorService.cs
- Remora.Discord.Commands/Services/Execution/IPostExecutionEvent.cs
- Remora.Discord.Commands/Services/Execution/IPreExecutionEvent.cs
- Tests/Remora.Discord.Commands.Tests/ContextTests.cs
This PR reworks the pre- and post-execution event API, making it a bit less tedious to work with. Furthermore, it also alters `InteractionContext`, providing more data useful to both command implementations and execution events.
> [WIP] Rework pre- and post-execution event API

- Directory.Build.props
- stylecop.ruleset
This PR fixes a few issues in the settings shared by each project.
These issues are encountered in Visual Studio 2019 (ver 16.11.1).
- Cannot find the `stylecop.ruleset` file in the IDE.
- Cannot edit the `stylecop.ruleset` file in the IDE because it says there are duplicate rules.
- Cannot build when using the shared project feature because the `stylecop.json` file is required to be in the root of the solution.
> Fix the settings shared by each project.

- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
- Backend/Remora.Discord.Gateway/Transport/WebSocketPayloadTransportService.cs
If RunAsync was called with an already cancelled token, this delay would throw an improperly handled TaskCanceledException. As a result, regular cleanup would be bypassed.
Also fixed certain transport service disconnect calls indicating they will reconnect when they won't.
This ensures the path of disconnection is followed as if the gateway itself requested it.
> Fix send/receive gateway tasks never completing

- Remora.Discord.Commands/Parsers/SnowflakeParser.cs
- Tests/Remora.Discord.Commands.Tests/Parsers/SnowflakeParserTests.cs
Snowflake parser could not handle mentions, only raw values. That meant slightly different behavior for interaction commands (user can choose the role/channel/user from a list - supply it as "mention"), but for message commands it would work with plain number only.
I also added some tests, I couldn't find any for `SnowflakeParser`, tell me if changing anything in them is needed.
> Add handling of mentions for SnowflakeParser

- Backend/Remora.Discord.API.Abstractions/API/Objects/Applications/IApplication.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Channels/IChannel.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Emojis/IEmoji.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Guilds/IGuild.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Guilds/IGuildMember.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Integrations/IIntegration.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IGuildApplicationCommandPermissions.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Invites/IInvite.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Messages/IMessage.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Permissions/IRole.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Presence/IPresence.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Users/IUser.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Voice/IVoiceState.cs
This change explicitly implements the partial variants of interfaces on the full interface for types that have a partial variant. Effectively, this allows you to use non-partial objects (`Application`, `Message`, etc) as their partial counterparts without any extra code, streamlining some interactions between various API methods.
As it stands, everything seems to work as expected, but I'd like some feedback before I merge this.
> Explicitly implement partial variants of interfaces

- Remora.Discord.Hosting/Remora.Discord.Hosting.csproj
Removed unneeded package reference that is automatically referenced inside of Microsoft.Extensions.DependencyInjection which is referenced in the Remora.Discord.API project, which is referenced by the Remora.Discord.Rest project, which is referenced by the Remora.Discord.Gateway project, which is then referenced by the Remora.Discord.Hosting project.
> Removed unneeded Package Reference in the Hosting project.

- Backend/Remora.Discord.API.Abstractions/Results/DiscordError.cs
Adds the 50101 JSON error code to Discord Error.
> This server needs more boosts to perform this action
> Added 50101 to DiscordError.cs

- Backend/Remora.Discord.API.Abstractions/API/Objects/Permissions/IDiscordPermissionSet.cs
- Backend/Remora.Discord.API/API/Objects/Permissions/DiscordPermissionSet.cs
- Tests/Remora.Discord.API.Tests/API/Objects/Permissions/DiscordPermissionSetTests.cs
Following on from discussion in the Discord earlier, this method on the `IDiscordPermissionSet` interface provides a means to retrieve the permissions contained within the set in the form of the `DiscordPermission` enumeration.
I considered making this an extension method but felt it was fairly integral.
> Adds IDiscordPermissionSet#GetPermissions

- Backend/Remora.Discord.API/API/Objects/Permissions/DiscordPermissionSet.cs
- Tests/Remora.Discord.API.Tests/API/Objects/Permissions/DiscordPermissionSetTests.cs
Firstly, this PR fixes my recent `DiscordPermissionSet#GetPermissions` addition by removing an erronous integer cast and subsequently re-writing the algorithm for a ~15x speed improvement after some benchmarking. Shoulda copied your logic straight off the bat, Jax 😄.
Secondly, I've noticed that with the addition of the latest permission `StartEmbeddedActivities`, `BigInteger` was starting to consider some permission values as being signed, causing at least `HasPermission` to fail (specifically when trying to retrieve the byte array of the value in an unsigned form). To resolve this, the value is now explicitly marked as unsigned upon construction.
> Fix DiscordPermissionSet#GetPermissions and Value storage.

- Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IApplicationCommandInteractionDataResolved.cs
- Backend/Remora.Discord.API/API/Objects/Interactions/ApplicationCommandInteractionDataResolved.cs
- Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs
- Tests/Remora.Discord.Tests/Samples/Objects/APPLICATION_COMMAND_INTERACTION_DATA_RESOLVED/APPLICATION_COMMAND_INTERACTION_DATA_RESOLVED.json
This property is included with resolved application command data when receiving a message command interaction.
Note that there are failing tests related to ephemeral commands. These don't appear to be related to this addition and instead were introduced in [#19a0664](https://github.com/Nihlus/Remora.Discord/commit/19a066415c257a3c14f8e0d4e0247d97591cc9dd)
> Add Messages property to IApplicationCommandInteractionDataResolved

- Remora.Discord.Commands/Attributes/ChannelTypeAttribute.cs
- Remora.Discord.Commands/Attributes/ChannelTypesAttribute.cs
- Remora.Discord.Commands/Extensions/CommandTreeExtensions.cs
- Samples/SlashCommands/Commands/HttpCatCommands.cs
- Tests/Remora.Discord.Commands.Tests/Data/InternalLimits/ChannelTypesAttributeOnlyOnChannelParameter.cs
- Tests/Remora.Discord.Commands.Tests/Data/InternalLimits/ChannelTypesAttributeRequiresAtLeastOneValue.cs
- Tests/Remora.Discord.Commands.Tests/Data/Valid/TypedCommands.cs
- Tests/Remora.Discord.Commands.Tests/Extensions/CommandTreeExtensionTests.cs
Adds the `ChannelTypesAttribute` to the commands library, allowing channel types to be specified on `IChannel` command parameters, aiding autocomplete. This builds on #107.
```csharp
[Command("channel-type-demo")]
public async Task<IResult> ChannelTypeDemoCommandAsync(
[ChannelTypes(ChannelType.GuildText, ChannelType.GuildVoice)] IChannel channel)
{
...
}
```
> Add ChannelTypesAttribute

- Backend/Remora.Discord.API.Abstractions/API/Gateway/Events/Guilds/IGuildMemberUpdate.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Guilds/IGuildMember.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Guilds/IPartialGuildMember.cs
- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestGuildAPI.cs
- Backend/Remora.Discord.API/API/CDN.cs
- Backend/Remora.Discord.API/API/Gateway/Events/Guilds/GuildMemberAdd.cs
- Backend/Remora.Discord.API/API/Gateway/Events/Guilds/GuildMemberUpdate.cs
- Backend/Remora.Discord.API/API/Objects/Guilds/GuildMember.cs
- Backend/Remora.Discord.API/API/Objects/Guilds/PartialGuildMember.cs
- Backend/Remora.Discord.Caching/API/CachingDiscordRestGuildAPI.cs
- Backend/Remora.Discord.Caching/Responders/EarlyCacheResponder.cs
- Backend/Remora.Discord.Rest/API/Guilds/DiscordRestGuildAPI.cs
- Samples/UnknownEventLogger/Responders/UnknownEventResponder.cs
- Tests/Remora.Discord.API.Tests/API/CDNTests.cs
- Tests/Remora.Discord.Rest.Tests/API/Guild/DiscordRestGuildAPITests.cs
Started implementing the changes made in [commit d49d34b](https://github.com/discord/discord-api-docs/commit/d49d34bd5ffa3df659eb92bfa743af79c607d5cd) to the DAPI docs.
Note that there is a caveat here. The DAPI docs note that the new `avatar` field is required, however my current implementation  marks it as optional, as this is the behaviour observed from the API. I have created an [issue on the docs regarding this](https://github.com/discord/discord-api-docs/issues/3883).
I decided to do this in order to have correct functionality of the feature at this time, and because the same workaround has been utilised for role icons.
> Add Per-Guild Avatars and ModifyCurrentMember

- Remora.Discord.Commands/Feedback/Messages/FeedbackMessageOptions.cs
- Remora.Discord.Commands/Feedback/Services/FeedbackService.cs
- Samples/DiceRoller/Commands/DiceRollCommands.cs
- Samples/SlashCommands/Commands/HttpCatCommands.cs
Added a `FeedbackMessageOptions` record and implemented support for it in the `FeedbackService`. This allows setting the following additional options common to both normal and interaction response messages when using the `FeedbackService`:
- `IsTTS`
- `File`
- `AllowedMentions`
- `MessageComponents`
There is a slight breaking change in that existing consumers of some methods will need to explicitly name the cancellation token parameter, e.g.
```csharp
-- SendContextualEmbedAsync(Embed embed, CancellationToken ct = default)
-- await SendContextualEmbedAsync(embed, ct);
++ SendContextualEmbedAsync(Embed embed, FeedbackMessageOptions? options = null, CancellationToken ct = default)
++ await SendContextualEmbedAsync(embed, ct: ct);
``
> Add FeedbackMessageOptions to expose additional options on feedback messages.

- Backend/Remora.Discord.API.Abstractions/API/Gateway/Events/Invites/IInviteCreate.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Invites/IInvite.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Invites/IPartialInvite.cs
- Backend/Remora.Discord.API/API/Gateway/Events/Invites/InviteCreate.cs
- Backend/Remora.Discord.API/API/Objects/Invites/Invite.cs
- Backend/Remora.Discord.API/API/Objects/Invites/PartialInvite.cs
- Tests/Remora.Discord.Tests/Samples/Gateway/Events/INVITE_CREATE/INVITE_CREATE.json
As noted in the Discord, the existing handling of invites from the API is invalid when it comes to ``target_application``. We have incorrectly typed this as a Snowflake, when in reality it is a partial application object.
You can find this definition on the Discord documentation, [here](https://discord.com/developers/docs/resources/invite#invite-object-invite-structure).
I've also gone ahead and added support for this field to the [Invite Create gateway event](https://discord.com/developers/docs/topics/gateway#invite-create), and corrected the (presumably changed?) field name, ``target_type``. Thanks to Falcon in the Discord for pointing this out.
Fixes #117.
> Fix incorrect handling of target_application in invites API

- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
This introduces a `Latency` property to the `DiscordGatewayClient`. This property is updated upon receiving a heartbeat and calculated from the time taken between sending a heartbeat and it being acknowledged. Hence providing an estimate of round-trip latency to the gateway.
> Add DiscordGatewayClient#Latency

- Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs
This PR adds an additional parameter to `AddDiscordCommands`, which simply skips over adding the default `AddCommandResponder` if set to false. 
In theory this should make it easier and potentially more efficient (perhaps a micro-optimization, but optimization is optimization) to stub in a responder of the end user's choosing, with the typical use-case being guild-specific prefixes.
Not sure if I should've written a test for this or anything, given it's something so simple, but do feel free to inform me if I've done something wrong.
> Omittable default responders

- Backend/Remora.Discord.Caching/Services/CacheService.cs
Fixed an issue where channels were being cached under the guild ID, causing cache to be constantly overwritten, and channels to not be cached correctly.
I also added parentheses to the type check, as it would cause an edge case where group DMs would be cached "incorrectly"; at least, I can't imagine that was inentional either.
> Fix channel caching on `GUILD_CREATE`

- Backend/Remora.Discord.API/API/DiscordSnowflake.cs
- Backend/Remora.Discord.Rest/API/Channels/DiscordRestChannelAPI.cs
- Backend/Remora.Discord.Rest/API/Interactions/DiscordRestInteractionAPI.cs
- Backend/Remora.Discord.Rest/API/Webhooks/DiscordRestWebhookAPI.cs
- Remora.Discord.Commands/Parsers/ChannelParser.cs
- Remora.Discord.Commands/Parsers/EmojiParser.cs
- Remora.Discord.Commands/Parsers/GuildMemberParser.cs
- Remora.Discord.Commands/Parsers/RoleParser.cs
- Remora.Discord.Commands/Parsers/UserParser.cs
- Samples/Autocomplete/Program.cs
- Samples/SlashCommands/Program.cs
- Introduced the `DiscordSnowflake` helper class which provides means to initialise `Snowflake` instances with the correct epoch.
- Replaced existing `Snowflake` instantiations to ensure that the correct epoch is used.
> Add DiscordSnowflake and fix Snowflake instantiation

- Remora.Discord.Commands/Contexts/InteractionContext.cs
- Remora.Discord.Commands/Responders/AutocompleteResponder.cs
- Remora.Discord.Commands/Responders/InteractionResponder.cs
- Tests/Remora.Discord.Commands.Tests/ContextTests.cs
Adds the `InteractionContext#Message` property. This is included in `INTERACTION_CREATE` gateway events generated by message components, and stores the message that the component was attached to.
> Add InteractionContext#Message

- Remora.Discord.Commands/Attributes/MaxValueAttribute.cs
- Remora.Discord.Commands/Attributes/MinValueAttribute.cs
This PR fixed the Nullable Attributes MaxValue and MinValue, which doesn't need to be nullable, since when its null you wouldn't use the attribute 
Furthermore, it causes ` CS0181 Attribute constructor parameter ‘min/maxValue’ has type ‘long?’, which is not a valid attribute parameter type` when using them
> Fix Nullable MaxValue and MinValue

- Remora.Discord.Commands/Remora.Discord.Commands.csproj
- Remora.Discord.Commands/Responders/CommandResponder.cs
- Remora.Discord.Commands/Responders/InteractionResponder.cs
- Remora.Discord.Commands/Services/ITreeNameResolver.cs
- Remora.Discord.Commands/Services/SlashService.cs
- Samples/Autocomplete/Program.cs
- Samples/DiceRoller/Program.cs
- Samples/Interactivity/Program.cs
- Samples/SlashCommands/Program.cs
This PR augments Remora.Discord.Commands in order to support multiple registered command trees.
Primarily, this means two things:
1. Slash command registration must now be done on a tree-by-tree basis. SlashService has been updated to accept `string? treeName` where appropriate.
2. The name of the tree to use can be selected at runtime on a per-command basis via `ITreeNameResolver`. This is a service interface that library consumers can implement and register with the service provider, through which an appropriate tree name for the current command context can be provided. Optionally, this interface also allows the implementer to indicate that they'd like the default tree to be used as a fallback in case the named tree can't execute the command. By default, no service implementing …
> Support multiple command trees

- Remora.Discord.Extensions/Embeds/EmbedBuilder.cs
Modifies `WithAuthor()` and `WithFooter()` to accept null strings as default instead of empty strings to prevent an error when building the corresponding `EmbedAuthor` and `EmbedFooter` objects.
Modifies the `AddField()` and `SetFields()` methods to return `Result<EmbedBuilder>` for chaining.
> Adds some EmbedBuilder improvments and bug fixes

- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
- Backend/Remora.Discord.Gateway/DiscordGatewayClientOptions.cs
Allows `large_threshold` to be specified in the config. This was previously absent, and thus defaulted to 50. For consistency the default in the config is also 50, but is now adjustable
> Allow `large_threshold` to be specified

- Backend/Remora.Discord.Caching/Services/CacheService.cs
There are times where you intentionally want to avoid caching certain data (such as presence data) or anything else you know you won't be using.
The default TTL of 30s is *fine*, but in the case of presence data, the events are streamed so frequently that the cache is always full of this data.
> Add support for "cache dodging"

- Remora.Discord.Commands/Conditions/Attributes/RequireBotDiscordPermissionsAttribute.cs
- Remora.Discord.Commands/Conditions/RequireBotDiscordPermissionsCondition.cs
- Remora.Discord.Commands/Conditions/RequireDiscordPermissionCondition.cs
- Tests/Remora.Discord.Commands.Tests/Conditions/RequireBotPermissionsConditionTests.Cases.And.cs
- Tests/Remora.Discord.Commands.Tests/Conditions/RequireBotPermissionsConditionTests.Cases.Not.cs
- Tests/Remora.Discord.Commands.Tests/Conditions/RequireBotPermissionsConditionTests.Cases.Or.cs
- Tests/Remora.Discord.Commands.Tests/Conditions/RequireBotPermissionsConditionTests.Cases.Xor.cs
- Tests/Remora.Discord.Commands.Tests/Conditions/RequireBotPermissionsConditionTests.Cases.cs
- Tests/Remora.Discord.Commands.Tests/Conditions/RequireBotPermissionsConditionTests.cs
- Tests/Remora.Discord.Commands.Tests/Conditions/RequireDiscordPermissionConditionTests.cs
- Tests/Remora.Discord.Commands.Tests/Remora.Discord.Commands.Tests.csproj
Adds a new condition (and attribute) that requires the bot to have certain permissions in the channel a command is invoked within.
Test to come; I have other things I'd like to PR as well.
> Add `RequireBotPermissionsCondition`

- Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs
In #155, I had overlooked the fact that conditions need to be registered to actually function.
This simple PR fixes that.
> Register RequireBotDiscordPermissionsCondition

- Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs
Catches an expected OCE that would've otherwise bubbled up to the Host/AppDomain when stopping the dispatch service.
> fix(Dispatch): Don't throw when disposing

- Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs
In the current state when a slash command has an attachment as parameter the JSON converter is unable to deserialize the Snowflake key in the Attachments dictionary of IApplicationCommandInteractionDataResolved
> Fix Attachments in SlashCommands

- Backend/Remora.Discord.Rest/API/RateLimitBucket.cs
The `X-RateLimit-Reset` header is currently parsed based on the systems locale.
Some locales use a `,` as decimal separator and some locales use `.` for separation.
Therefore the double must be parsed indepedent of the systems locale.
> Parse X-RateLimit-Reset independent of system culture

- Backend/Remora.Discord.Caching/KeyHelpers.cs
Cache key returned by `CreateGuildInvitesCacheKey` started with `Guid:` instead of `Guild:`.
Fixed by switching to using `CreateGuildCacheKey` as other methods do too.
> Fix typo in `CreateGuildInvitesCacheKey` by using `CreateGuildCacheKey`

- Remora.Discord.Commands/Extensions/CommandTreeExtensions.cs
Early bailout doesn't check whether it is a description for a slash command, which is allowed to have one.
Introduced in 586a0aeef3cc28b9b6498ea6c59b40507c1603ec
> Fix early bailout not checking for slash command

- Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs
This PR adds an optimization for responder dispatch which replaces `MethodInfo` calls with delegates. In theory dispatch is now 17 times faster, but actual performance gains will probably be negligible. Below are the results of benchmarks of purely just MethodInfo versus delegate calls:
```fix
|          Method |       Mean |     Error |    StdDev | Allocated |
|---------------- |-----------:|----------:|----------:|----------:|
|      MethodInfo | 123.626 ns | 1.8388 ns | 1.5355 ns |      32 B |
| UnboundDelegate |   8.015 ns | 0.1286 ns | 0.1203 ns |         - |
|   BoundDelegate |   7.197 ns | 0.0738 ns | 0.0691 ns |         - |
```
> Use delegates instead of MethodInfo for dispatch

- Remora.Discord.Extensions/Formatting/AnsiBackgroundColor.cs
- Remora.Discord.Extensions/Formatting/AnsiForegroundColor.cs
- Remora.Discord.Extensions/Formatting/AnsiStringBuilder.cs
- Remora.Discord.Extensions/Formatting/AnsiStyle.cs
- Tests/Remora.Discord.Extensions.Tests/AnsiStringBuilderTests.cs
Provides a class to build an ANSI formatted string that is supported by Discords ANSI code blocks.
- Only works in ANSI code blocks
- Supported only on desktop clients
The implementation of the build builds the string as in this gist:  [here](https://gist.github.com/MazeXP/617fcf7c8d632cfbf3a7376753df6307#file-6-preview-md)
The class is used like this: [here](https://gist.github.com/MazeXP/617fcf7c8d632cfbf3a7376753df6307#file-5-sample-cs)
I am open to have a discussion about this implementation and also open for suggestions.
> Add ANSI formatting string builder

- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestApplicationAPI.cs
- Backend/Remora.Discord.Rest/API/Applications/DiscordRestApplicationAPI.cs
- Tests/Remora.Discord.Rest.Tests/API/Applications/DiscordRestApplicationAPITests.cs
- stylecop.json
This PR adds missing parameters (DefaultMemberPermissions, DMPermission) to the appropriate methods on IDiscordRestApplicationAPI and it's implementation
> Add missing permission parameters for application methods

- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestApplicationAPI.cs
- Backend/Remora.Discord.Rest/API/Applications/DiscordRestApplicationAPI.cs
Some methods have incorrect type for `defaultMemberPermissions` parameter, docs refer to it as `default_member_permissions?	?string`.
In code they are currently `Optional<IDiscordPermissionSet>`, but it should be `Optional<IDiscordPermissionSet?>`
Affected methods:
- `CreateGlobalApplicationCommandAsync`
- `EditGlobalApplicationCommandAsync`
- `CreateGuildApplicationCommandAsync`
- `EditGuildApplicationCommandAsync`
> fix nullability of defaultMemberPermissions param

- Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs
- Tests/Remora.Discord.Tests/Samples/Gateway/Commands/IDENTIFY/IDENTIFY.OMIT_NULLS.json
- Tests/Remora.Discord.Tests/Samples/Gateway/Commands/IDENTIFY/IDENTIFY.json
- Tests/Remora.Discord.Tests/Samples/Objects/CONNECTION_PROPERTIES/CONNECTION_PROPERTIES.json
> Remove deprecated prefix in IIdentify connection fields [API v11]

- Backend/Remora.Discord.Gateway/Extensions/ServiceCollectionExtensions.cs
- Backend/Remora.Discord.Gateway/Remora.Discord.Gateway.csproj
- Backend/Remora.Discord.Gateway/ResponderDispatchOptions.cs
- Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs
- Tests/Remora.Discord.Gateway.Tests/Remora.Discord.Gateway.Tests.csproj
- Tests/Remora.Discord.Gateway.Tests/Tests/DiscordGatewayClientTests.cs
This PR adds the ability to cuztomize and parallelize dispatch of responders. This is certainly tuned toward larger bots, but could bring some performance benefits overall.
It's worth noting that in very high throughput situations, parallelizing dispatch can cause race conditions in entity states, especially if using a backing store such as Redis.
> Add customization and parallelization to responder dispatching

- .github/workflows/dotnet.yml
I think storing only 5 of the bleeding edge package versions would help avoid going over github's 500 MB free limit which would save money 💵.
> Prune packages older than 5 versions.

- Backend/Remora.Discord.Gateway/Extensions/ServiceCollectionExtensions.cs
- Backend/Remora.Discord.Rest/Constants.cs
- Backend/Remora.Discord.Rest/DiscordTokenType.cs
- Backend/Remora.Discord.Rest/Extensions/HttpRequestMessageExtensions.cs
- Backend/Remora.Discord.Rest/Extensions/RestRequestBuilderExtensions.cs
- Backend/Remora.Discord.Rest/Extensions/ServiceCollectionExtensions.cs
- Backend/Remora.Discord.Rest/Handlers/AuthorizationHandler.cs
- Backend/Remora.Discord.Rest/Handlers/TokenAuthorizationHandler.cs
- Backend/Remora.Discord.Rest/ITokenStore.cs
- Backend/Remora.Discord.Rest/Polly/DiscordRateLimitPolicy.cs
- Tests/Remora.Discord.Commands.Tests/ContextTests.cs
- Tests/Remora.Discord.Commands.Tests/TestBases/CommandResponderTestBase.cs
- Tests/Remora.Discord.Rest.Tests/Polly/DiscordRateLimitPolicyTests.cs
- Tests/Remora.Discord.Rest.Tests/TestBases/RestAPITestBase.cs
- Tests/Remora.Discord.Tests/Tests/Core/TokenStore/TokenStoreTests.cs
In the following the Authrization Header is now being added by a DelegatinHandler.
This allows to skip the addition of the Authorization header in special cases. (e.g. WebHooks)
An extension method has been added to the RestRequestBuilder class to skip the authorization. `b.SkipAuthorization()`
> Externalize adding of Authorization header

- Backend/Remora.Discord.Rest/API/Webhooks/DiscordRestWebhookAPI.cs
- Tests/Remora.Discord.Rest.Tests/API/Webhooks/DiscordRestWebhookAPITests.cs
Some webhook endpoints rely on a token themself for authorization.
Therefore the authorization by header should be skipped.
- [Get Webhook with Token](https://discord.com/developers/docs/resources/webhook#get-webhook-with-token)
- [Modify Webhook with Token](https://discord.com/developers/docs/resources/webhook#modify-webhook-with-token)
- [Delete Webhook with Token](https://discord.com/developers/docs/resources/webhook#delete-webhook-with-token)
> Skip authorization for Webhook endpoints that use a token

- Backend/Remora.Discord.API.Abstractions/API/Gateway/Events/ConnectingResuming/IReady.cs
- Backend/Remora.Discord.API/API/Gateway/Events/ConnectingResuming/Ready.cs
- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
- Tests/Remora.Discord.Gateway.Tests/Constants.cs
- Tests/Remora.Discord.Gateway.Tests/Tests/DiscordGatewayClientTests.cs
- Tests/Remora.Discord.Tests/Samples/Gateway/Events/READY/READY.json
Implements support for the `resume_gateway_url`, sent with the `ready` payload to indicate which endpoint to connect to when resuming a gateway connection.
See: discord/discord-api-docs#5282
> Support Resume Gateway URL

- Remora.Discord.Commands/Extensions/CommandTreeExtensions.cs
- Tests/Remora.Discord.Commands.Tests/Data/Valid/NumericalParameterWithValueConstraints.cs
- Tests/Remora.Discord.Commands.Tests/Extensions/CommandTreeExtensionTests.cs
closes #234 
Added some tests and fixed the bug I found. While working on this I also noticed that the min and max value attributes can't be applied to integers, should this be changed?
> Fix validation for MinValue and MaxValue attributes

- Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IInteractionMessageCallbackData.cs
The current documentation was very unclear in it's purpose, especially given that it's not intended to be set directly, which would result in an error.
> Reword docs for attachments on interactions

- Remora.Discord.Hosting/Extensions/HostBuilderExtensions.cs
This PR adds the `buildClient` parameter from AddDiscordGateway to AddDiscordService; normally it's not possible to use the hosting framework if passing this parameter is desired.
> Add `buildClient` parameter to HostBuilderExtensions.AddDiscordService

- Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs
Normally, The call to IServiceProvider.GetRequiredService in ResponderDispatchService.DispatchEventAsync isn't guarded by a try-catch; however, GetService can throw an exception if the service activation fails for some reason. This causes an exception to be absorbed instead of rethrown as an Error (which exceptions thrown by RespondAsync _will_).
This PR moves the call to GetRequiredService into the `try`.
This PR does not fix the underlying problem of unguarded exceptions within DispatchEventAsync being swallowed; it is unclear to me what should happen in that case, however I believe putting the GetRequiredService call inside the `try` is still the correct fix for the immediate problem.
> Guard GetRequiredService call in try-catch in DispatchEventAsync

- Backend/Remora.Discord.Caching.Redis/Services/RedisCacheProvider.cs
The current implementation of `RedisCacheProvider.CacheAsync` serializes into a string, then passes that to the RedisCache; passing a byte array should be more friendly to the System.Text.Json serializer and reduce string processing overhead.
This PR uses `JsonSerializer.SerializeToUtf8Bytes` and the `byte[]` overload of `IDistributedCache.SetAsync` for this.
> Make RedisCacheProvider pass values as byte[] directly instead of serializing to string

- Remora.Discord.Extensions/Attributes/ResponderAttribute.cs
- Remora.Discord.Extensions/Attributes/ResponderGroupAttribute.cs
- Remora.Discord.Extensions/Extensions/ServiceCollectionExtensions.cs
- Remora.Discord.Extensions/Remora.Discord.Extensions.csproj
- Tests/Remora.Discord.Extensions.Tests/Samples/TestCommand.cs
- Tests/Remora.Discord.Extensions.Tests/Samples/TestResponder.cs
- Tests/Remora.Discord.Extensions.Tests/ServiceCollectionExtensionsTests.cs
This PR adds helper methods that register responders and commands based on assembly discovery.
This was pitched by @cmsteffey, since other libraries have this functionality (usually in addition to explicit registrations, such as D#+)
> Add assembly discovery extension methods

- Remora.Discord.Commands/Extensions/CommandTreeExtensions.cs
- Samples/Localization/Commands/HttpCatCommands.cs
- Samples/SlashCommands/Commands/HttpCatCommands.cs
- Tests/Remora.Discord.Commands.Tests/Data/DiscordLimits/ContextMenusWithoutParametersAreNotSupported.cs
- Tests/Remora.Discord.Commands.Tests/Data/Valid/GroupWithContextMenuAndCommand.cs
- Tests/Remora.Discord.Commands.Tests/Data/Valid/GroupWithContextMenus.cs
- Tests/Remora.Discord.Commands.Tests/Extensions/CommandTreeExtensionTests.cs
This PR fixes the issue that arises when one has a context menu command without any parameter.
As it will always expect at least 1 parameter. (`user` for User commands and `message` for Message commands)
Therefore an exception will now be also thrown when the command does not have any parameters at all.
> Throw exception for invalid parameters when registering context menu commands

- Backend/Remora.Discord.API.Abstractions/API/Objects/Applications/ApplicationRoleConnectionMetadataType.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Applications/IApplication.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Applications/IApplicationRoleConnectionMetadata.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Applications/IPartialApplication.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Users/IApplicationRoleConnection.cs
- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestApplicationAPI.cs
- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestUserAPI.cs
- Backend/Remora.Discord.API/API/Objects/Applications/ApplicationRoleConnectionMetadata.cs
- Backend/Remora.Discord.API/API/Objects/Applications/PartialApplication.cs
- Backend/Remora.Discord.API/API/Objects/Users/ApplicationRoleConnection.cs
- Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs
- Backend/Remora.Discord.Caching/API/CachingDiscordRestUserAPI.cs
- Backend/Remora.Discord.Caching/KeyHelpers.cs
- Backend/Remora.Discord.Rest/API/Applications/DiscordRestApplicationAPI.cs
- Backend/Remora.Discord.Rest/API/Users/DiscordRestUserAPI.cs
- Tests/Remora.Discord.API.Tests/API/Objects/ApplicationRoleConnections/ApplicationRoleConnectionMetadataTests.cs
- Tests/Remora.Discord.API.Tests/API/Objects/Users/ApplicationRoleConnectionTests.cs
- Tests/Remora.Discord.Rest.Tests/API/Applications/DiscordRestApplicationAPITests.cs
- Tests/Remora.Discord.Rest.Tests/API/Users/DiscordRestUserAPITests.cs
- Tests/Remora.Discord.Tests/Samples/Objects/APPLICATION_ROLE_CONNECTION/APPLICATION_ROLE_CONNECTION.json
- Tests/Remora.Discord.Tests/Samples/Objects/APPLICATION_ROLE_CONNECTION_METADATA/APPLICATION_ROLE_CONNECTION_METADATA.json
This PR implements the new application role connections endpoints and objects as documented in https://github.com/discord/discord-api-docs/pull/5668
> Implement role connections API endpoints and objects

- Remora.Discord.Commands/Extensions/ParameterShapeExtensions.cs
- Tests/Remora.Discord.Commands.Tests/Extensions/ParameterShapeExtensionsTests.cs
With this PR it will allow to also use `IPartial*` inside of command parameters.
I've also took the opportunity to add tests for the `ParameterShapeExtensions`.
> Handle IPartial* correctly when updating slash commands

- Samples/Caching/Program.cs
The AddDiscordCaching call was erroneously when it was first replaced by AddDiscordRedisCaching and the removed when removing the dependency of Redis.
> Readd AddDiscordCaching call to Caching sample

- Remora.Discord.Hosting/Extensions/HostBuilderExtensions.cs
.NET 7 adds a new `HostApplicationBuilder` API in the style of the simplified `WebApplicationBuilder` from ASP.NET Core 6. It does not implement `IHostBuilder`, so the existing extension that adds the Remora hosted service does not work with it. The recommended pattern for `HostApplicationBuiler` is to add an extension method for `IServiceCollection` (`builder.Services.AddDiscordService(...)`).
> Add overload of AddDiscordService for use with HostApplicationBuilder

- Remora.Discord.Extensions/Extensions/ServiceCollectionExtensions.cs
- Remora.Discord.Extensions/Remora.Discord.Extensions.csproj
In the previous PR, there was a bug that was overlooked regarding to the sweeping nature of registering *all* commands.
While technically this was mitigated by the `filter` parameter, this required intiricate knowledge of the implementation of interactivity and action from the user.
> Don't register interaction groups with assembly-scanning

- Backend/Remora.Discord.Caching.Abstractions/CacheKey.cs
These types should be sealed to make it clear that they are not to be extended.
> Seal StringCacheKey/ResourceCacheKey

- Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IMessageComponentData.cs
- Backend/Remora.Discord.API/API/Objects/Interactions/MessageComponentData.cs
- Remora.Discord.Interactivity/Responders/InteractivityResponder.cs
- Tests/Remora.Discord.Tests/Samples/Objects/MESSAGE_COMPONENT_DATA/MESSAGE_COMPONENT_DATA.json
The Discord API docs denote that this field should contain a list of `ISelectOption` values. However, in their samples and as identified through testing, it actually always contains a list of strings.
I will open a PR on the Discord API docs about this issue in short order, and link it here once done.
> Re-type IMessageComponentData.cs#Values to an optional list of strings

- Samples/Interactivity/Interactions/SelectMenuInteractions.cs
- Samples/Interactivity/Interactions/StatefulInteractions.cs
- Samples/Interactivity/Program.cs
A couple of small updates to the interactivity sample:
- Renamed `ColourDropdownInteractions.cs` to `SelectMenuInteractions.cs`, now that it contains samples for various select menu types.
- Fixed the injection of the interaction context into `SelectMenuInteractions`, by injecting the interface (`IInteractionCommandContext`).
- Injected the correct generic logger type in `StatefulInteractions`.
> Interactivity sample updates

- Backend/Remora.Discord.API.Abstractions/API/Objects/Messages/IEmbedImage.cs
Change "thumbnail" to "image" in the documentation, as it should be.
> Fix misnomer in IEmbedImage

- Remora.Discord.Pagination/Interactions/PaginationInteractions.cs
`PaginationInteractions` tries to consume `InteractionContext` via DI, which isn't available and causes an exception at runtime. This PR switches it to consume the interface instead.
> Fix dependency injection exception for PaginationInteractions

- .config/dotnet-tools.json
- .github/workflows/dotnet.yml
- Backend/Remora.Discord.API/API/Gateway/Commands/RequestGuildMembers.cs
- Backend/Remora.Discord.API/API/Objects/Interactions/InteractionAutocompleteCallbackData.cs
- docfx/docfx_project/docfx.json
- docfx/docfx_project/templates/custom_template/partials/head.tmpl.partial
- docfx/docfx_project/templates/custom_template/partials/navbar.tmpl.partial
- docfx/docfx_project/templates/custom_template/styles/main.css
- docfx/docfx_project/templates/custom_template/styles/main.js
- docfx/scripts/_common.sh
- docfx/scripts/build.sh
- docfx/scripts/prepare.sh
- docfx/templates/index.html
This PR customizes the build workflow to publish multiple versions of
the documentation.
It is setup to always keep the `main` branch and the latest 5 tags (variable `KEEP_TAG_VERSIONS`).
The `index.html` is edited on every build to redirect to the latest tag.
Before merging into `main` branch the `gh-pages` branch must be cleaned up, to consist only of following files:
```html
<html>
<head>
<meta http-equiv="refresh" content="0; url=./main" />
</head>
<body></body>
</html>
```
> DocFX: Multiple version support

- Samples/Interactivity/Commands/InteractiveCommands.cs
Discord does not allow an zero length string as value for TextInputComponent.
> TextInputComponent value must not be empty

- .gitmodules
- docfx/docfx_project/docfx.json
This PR shortens the anchors to members of a type in the documentation.
1. Strip Type FullName from UID
2. Append index based on occurence of member name per type
```
.../api/Remora.Discord.Rest.API.DiscordRestWebhookAPI.html#Remora_Discord_Rest_API_DiscordRestWebhookAPI_EditWebhookMessageAsync_Remora_Rest_Core_Snowflake_System_String_Remora_Rest_Core_Snowflake_Remora_Rest_Core_Optional_System_String__Remora_Rest_Core_Optional_System_Collections_Generic_IReadOnlyList_Remora_Discord_API_Abstractions_Objects_IEmbed___Remora_Rest_Core_Optional_Remora_Discord_API_Abstractions_Objects_IAllowedMentions__Remora_Rest_Core_Optional_System_Collections_Generic_IReadOnlyList_Remora_Discord_API_Abstractions_Objects_IMessageComponent___Remora_Rest_Core_Optional_System_Collections_Generic_IReadOnlyList_O …
```
> Shortens anchor links in documentation

- Backend/Remora.Discord.Gateway/Remora.Discord.Gateway.csproj
- Backend/Remora.Discord.Gateway/Transport/WebSocketPayloadTransportService.cs
- Directory.Packages.props
¹This PR only optimizes `WebSocketPayloadTransportService`'s `ReceiveAsync` method.
This PR is one of many that will tackle various issues mentioned in #254.
This one in particular relates to the performance (speed, allocations) concerns raised by the current implementation of receiving a payload (as implemented by the aforementioned class).
Notable changes are: 
- Using `CommunityToolKit.HighPerformance`
- Switching `WebSocketReceiveResult` to its struct-based alternative
- Using reusable² buffers
- Using `JsonSerializer.Deserialize<T>` instead of its async alternative
It should be considered that as a critical part of the library, it's important that this code is battle-tested, and not just validated by unit-tests. In theory, the logic of the receive flow has not changed, but there's …
> Optimize receving payloads¹

- Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs
In cases when a `PartialChannel` object has a `default_thread_rate_limit_per_user` property provided,
the deserialization would fail as it was trying to convert the TimeSpan using the default
`TimeSpanConverter` (expects string) instead of the `UnitTimeSpanConverter` (expects double/integer).
In addition I found a similiar discrepancy between `IAttachment` and `IPartialAttachment` (`duration_secs`),
so I got them also on par.
> Fix convert discrepancies between partial and non-partial type

- Backend/Remora.Discord.Caching/Responders/EarlyCacheResponder.cs
Fixes an issue that would cause some properties to not be null after updating even if the new property was null. `IsDefined` checks if 1) the value exists and 2) the value *is not null*. The second check causes problems, that's why I replaced it with `TryGet` which only cares about a value being present, regardless of whether it's null or not
> Do not use IsDefined when updating cached nullable properties in GuildMember

- Backend/Remora.Discord.Caching/Responders/EarlyCacheResponder.cs
Fixes an issue where `CommunicationDisabledUntil` would be empty when a cached member got updated, even if they were timed out
> Fill CommunicationDisabledUntil when updating cached GuildMember

- Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/InteractionContextType.cs
The enum values were off-by-one, causing HTTP 400 at registration.
> fix(api): Fix InteractionContextType values

- Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs
- Remora.Discord.Commands/Parsers/MessageParser.cs
- Remora.Discord.Commands/Parsers/PartialMessageParser.cs
This PR fixes an issue wherein Remora would not correctly pull from the context when resolving partial messages. This poses an issue where the user cannot access member information via the API (e.g., an HTTP bot).
The issue in question is that when presented with an `IPartialMessage` parameter, the parser will *always* attempt to resolve the message via REST, which, under normal circumstances *would* be fine; this is generally desirable behavior for text commands, but is detrimental to slash commands, and especially context menus where this is enforced (e.g., you *must* have the message parameter.)
Regardless, there is a very simple fix, but before that I wanted to explain why this is an issue to being with.
---
The issue doesn't lie in the actual API logic, but the delegation to the …
> fix(commands): Fix handling of pulling context

- Backend/Remora.Discord.API.Abstractions/API/Objects/Invites/IInviteWithMetadata.cs
- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestGuildAPI.cs
- Backend/Remora.Discord.API/API/Objects/Invites/InviteWithMetadata.cs
- Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs
- Backend/Remora.Discord.Caching/API/CachingDiscordRestGuildAPI.cs
- Backend/Remora.Discord.Rest/API/Guilds/DiscordRestGuildAPI.cs
- Tests/Remora.Discord.API.Tests/API/Objects/Invites/InviteWithMetadataTests.cs
- Tests/Remora.Discord.Tests/Samples/Objects/INVITE_WITH_METADATA/INVITE_WITH_METADATA.json
- Tests/Remora.Discord.Tests/Samples/Objects/INVITE_WITH_METADATA/INVITE_WITH_METADATA.nulls.json
- Tests/Remora.Discord.Tests/Samples/Objects/INVITE_WITH_METADATA/INVITE_WITH_METADATA.options.json
Adds the keys in the invite metadata object (https://discord.com/developers/docs/resources/invite#invite-metadata-object) to the type returned by GET /guilds/{guildID}/invites.
> Add invite metadata to guild invites response

- Backend/Remora.Discord.API.Abstractions/API/Objects/WebhookEvents/IApplicationAuthorizedWebhookEvent.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/WebhookEvents/IWebhookEvent.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/WebhookEvents/IWebhookEventPayload.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/WebhookEvents/WebhookEventPayloadType.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/WebhookEvents/WebhookEventType.cs
- Backend/Remora.Discord.API.Abstractions/Remora.Discord.API.Abstractions.csproj.DotSettings
- Backend/Remora.Discord.API/API/Objects/WebhookEvents/ApplicationAuthorizedWebhookEvent.cs
- Backend/Remora.Discord.API/API/Objects/WebhookEvents/WebhookEvent.cs
- Backend/Remora.Discord.API/API/Objects/WebhookEvents/WebhookEventPayload.cs
- Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs
- Backend/Remora.Discord.API/Remora.Discord.API.csproj.DotSettings
- Tests/Remora.Discord.API.Tests/API/Objects/WebhookEventTests/ApplicationAuthorizedWebhookEventTests.cs
- Tests/Remora.Discord.API.Tests/API/Objects/WebhookEventTests/WebhookEventPayloadTests.cs
- Tests/Remora.Discord.API.Tests/API/Objects/WebhookEventTests/WebhookEventTests.cs
- Tests/Remora.Discord.Tests/Samples/Objects/APPLICATION_AUTHORIZED_WEBHOOK_EVENT/APPLICATION_AUTHORIZED_WEBHOOK_EVENT.json
- Tests/Remora.Discord.Tests/Samples/Objects/APPLICATION_AUTHORIZED_WEBHOOK_EVENT/APPLICATION_AUTHORIZED_WEBHOOK_EVENT.optionals.json
- Tests/Remora.Discord.Tests/Samples/Objects/WEBHOOK_EVENT/WEBHOOK_EVENT.json
- Tests/Remora.Discord.Tests/Samples/Objects/WEBHOOK_EVENT_PAYLOAD/WEBHOOK_EVENT_PAYLOAD.json
https://discord.com/developers/docs/events/webhook-events#webhook-events
> Add support for incoming webhook commands

- Samples/Interactivity/Interactions/SelectMenuInteractions.cs
A minor update to use the `OperationContextExtensions#TryGetUserID` extension to account for Discord's change to send user data in the `Member` field of an interaction response, rather than the `User` field.
Hence allowing the target of the feedback message to be reliably populated:
> Samples: Fix user target resolution on feedback responses

- Remora.Discord.Commands/Extensions/ApplicationCommandDataExtensions.cs
- Remora.Discord.Commands/Extensions/CommandTreeExtensions.cs
- Remora.Discord.Commands/Extensions/ParameterShapeExtensions.cs
- Tests/Remora.Discord.Commands.Tests/Extensions/CommandTreeExtensionTests.cs
This commit changes how Remora.Discord.Commands maps slash commands, enabling support for arrays to be parsed and accepted, despite Discord STILL not having support for this.
For better or worse, a snippet of code had to be removed:
```cs
var collectionType = parameter.GetActualParameterType();
if (!collectionType.IsCollection() && !collectionType.IsArray)
{
// Sanity check
throw new InvalidOperationException("Collection parameter was not a collection.");
}
```
^ For some reason, `.IsCollection()` returns...false? I gave up on trying to figure out why that was the case - the code still works fine and there's other validity checks elsewhere.
BREAKING-CHANGE: Commands with the structure of `name__numbers` (e.g. `param__1`) are *no longer valid* and will get erased by the pre-parsing step …
> Add array support for slash commands

- Remora.Discord.Pagination/Interactions/PaginationInteractions.cs
- Remora.Discord.Pagination/PaginatedAppearanceOptions.cs
- Remora.Discord.Pagination/PaginatedMessageData.cs
This pr makes the help & close buttons nullable and doesn't show them when there null and it adds the ability to add custom buttons. 
I did this pr to allow for more customizabiltity when using the pagination, since there isn't always the need for a help and close button, but sometimes there is the need for other custom buttons on it.
> Add custom buttons & ability to remove buttons to pagination

- Backend/Remora.Discord.Caching/Services/CacheService.cs
- Tests/Remora.Discord.Caching.Tests/CacheTests.cs
The code to copy overwritten values into the cache under an `EvictionCacheKey` was lost at some point. Reintroduce this functionality and add a test to ensure it is working.
> Fix CacheService.TryGetPreviousValueAsync
