Remora/Remora.Discord

- Remora.Discord.Commands/Conditions/Attributes/RequireUserGuildPermissionAttribute.cs
- Remora.Discord.Commands/Conditions/RequireContextCondition.cs
- Remora.Discord.Commands/Conditions/RequireUserGuildPermissionCondition.cs
- Remora.Discord.Commands/Results/ConditionNotSatisfiedError.cs
Added a condition for checking if the user has a given permission in the guild in which the command was executed. This is very useful for commands such as `!ban` etc. Also added an error that is used when a condition is not met.
> Add a condition for checking if the user has a given permission in the guild in which the command was executed.

- .idea/.idea.Remora.Discord/.idea/riderModule.iml
- Backend/Remora.Discord.Rest/API/Channels/DiscordRestChannelAPI.cs
- Tests/Remora.Discord.Rest.Tests/API/Channels/DiscordRestChannelAPITests.cs
> Fix bulk deleteion

- Remora.Discord.Commands/Responders/CommandResponder.cs
This should resolve the (minor) configuration issues as discussed on Discord @Nihlus
> Fixed issue where the CommandResponder was not using correct interface for CommandResponderOptions.

- Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs
- Remora.Discord.Commands/Responders/IInteractionResponderOptions.cs
- Remora.Discord.Commands/Responders/InteractionResponder.cs
- Remora.Discord.Commands/Responders/InteractionResponderOptions.cs
This requires users to handle interaction responses directly, allowing for more complex interaction scenarios.
Implemented as a non-breaking enhancement.
> Enhanced `InteractionResponder` to allow consumers to disable automatic interaction responses

- Remora.Discord.Commands/Conditions/RequireContextCondition.cs
Adds GuildPrivateThread and GuildPublicThread on ChannelContext.GuildCondition
> Adds GuildPrivateThread and GuildPublicThread on ChannelContext.GuildCondition

- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestChannelAPI.cs
- Backend/Remora.Discord.Rest/API/Channels/DiscordRestChannelAPI.cs
- Tests/Remora.Discord.Rest.Tests/API/Channels/DiscordRestChannelAPITests.cs
See https://discord.com/developers/docs/resources/channel#crosspost-message
> Add support for the Crosspost Message endpoint

- Backend/Remora.Discord.Rest/API/Invites/DiscordRestInviteAPI.cs
- Tests/Remora.Discord.Rest.Tests/API/Invites/DiscordRestInviteAPITests.cs
See: https://discord.com/developers/docs/resources/invite
> Fix Invite API

- Backend/Remora.Discord.Unstable/API/Objects/Interactions/ApplicationCommandInteractionData.cs
- Backend/Remora.Discord.Unstable/Extensions/ServiceCollectionExtensions.cs
- Backend/Remora.Discord.Unstable/Remora.Discord.Unstable.csproj
Added the undocumented select-menu values field. So select- menus can be usable.
> Added the undocumented select-menu values field to Unstable. So select- menus can be usable.

- Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/ApplicationCommandType.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IApplicationCommand.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IBulkApplicationCommandData.cs
- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestApplicationAPI.cs
- Backend/Remora.Discord.API/API/Gateway/Events/Interactions/ApplicationCommandCreate.cs
- Backend/Remora.Discord.API/API/Gateway/Events/Interactions/ApplicationCommandDelete.cs
- Backend/Remora.Discord.API/API/Gateway/Events/Interactions/ApplicationCommandUpdate.cs
- Backend/Remora.Discord.API/API/Objects/Interactions/ApplicationCommand.cs
- Backend/Remora.Discord.API/API/Objects/Interactions/BulkApplicationCommandData.cs
- Backend/Remora.Discord.Rest/API/Applications/DiscordRestApplicationAPI.cs
- Tests/Remora.Discord.Rest.Tests/API/Applications/DiscordRestApplicationAPITests.cs
- Tests/Remora.Discord.Tests/Samples/Gateway/Events/APPLICATION_COMMAND_CREATE/APPLICATION_COMMAND_CREATE.json
- Tests/Remora.Discord.Tests/Samples/Gateway/Events/APPLICATION_COMMAND_DELETE/APPLICATION_COMMAND_DELETE.json
- Tests/Remora.Discord.Tests/Samples/Gateway/Events/APPLICATION_COMMAND_UPDATE/APPLICATION_COMMAND_UPDATE.json
- Tests/Remora.Discord.Tests/Samples/Objects/APPLICATION_COMMAND/APPLICATION_COMMAND.json
https://discord.com/developers/docs/interactions/application-commands#user-commands
https://discord.com/developers/docs/interactions/application-commands#message-commands
The PR in question: https://github.com/discord/discord-api-docs/pull/3614
Please let me know if I forgot anything.
> Implement context menus (User command and Message commands)

- Backend/Remora.Discord.API.Abstractions/API/Objects/Channels/IThreadMetadata.cs
- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestChannelAPI.cs
- Backend/Remora.Discord.API.Abstractions/Results/DiscordError.cs
- Backend/Remora.Discord.API/API/Objects/Channels/ThreadMetadata.cs
- Backend/Remora.Discord.Caching/API/CachingDiscordRestChannelAPI.cs
- Backend/Remora.Discord.Rest/API/Channels/DiscordRestChannelAPI.cs
- Tests/Remora.Discord.Rest.Tests/API/Channels/DiscordRestChannelAPITests.cs
Threads update:
https://github.com/discord/discord-api-docs/commit/7ab5731e97262bcfdeb9278f8add0d555b98478d
New discord error:
https://github.com/discord/discord-api-docs/commit/85da043adec73d3cc07b2873f3db586ff5ecc618
> threads update and new discord error

- docs/custom/guides/getting-started.md
This makes some improvements and fixes some minor issues in the Getting Started guide.
> Update tutorial guide

- Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IApplicationCommandOption.cs
- Backend/Remora.Discord.API/API/Objects/Interactions/ApplicationCommandOption.cs
- Backend/Remora.Discord.API/Json/Converters/StringEnumListConverter.cs
WIP because i dont know if there's any logic i need to add regarding channel types
> Add ChannelTypes field to ApplicationCommandOption

- Remora.Discord.Commands/Parsers/GuildMemberParser.cs
- Remora.Discord.Commands/Parsers/RoleParser.cs
> Use context guild id in GuildMemberParser and RoleParser

- Backend/Remora.Discord.API.Abstractions/API/Gateway/Events/Guilds/IGuildMemberUpdate.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Guilds/IGuildMember.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Guilds/IPartialGuildMember.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Permissions/DiscordPermission.cs
- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestGuildAPI.cs
- Backend/Remora.Discord.API/API/Gateway/Events/Guilds/GuildMemberAdd.cs
- Backend/Remora.Discord.API/API/Gateway/Events/Guilds/GuildMemberUpdate.cs
- Backend/Remora.Discord.API/API/Objects/Guilds/GuildMember.cs
- Backend/Remora.Discord.API/API/Objects/Guilds/PartialGuildMember.cs
- Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs
- Backend/Remora.Discord.Rest/API/Guilds/DiscordRestGuildAPI.cs
- Tests/Remora.Discord.Rest.Tests/API/Guild/DiscordRestGuildAPITests.cs
https://github.com/discord/discord-api-docs/commit/b51c34f8f50ae8455f351f869ed22d025c1d2852
> Implement discord timeouts

- Backend/Remora.Discord.API.Abstractions/API/Objects/Channels/IThreadMetadata.cs
- Backend/Remora.Discord.API/API/Objects/Channels/ThreadMetadata.cs
- Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs
- Tests/Remora.Discord.Tests/Samples/Objects/THREAD_METADATA/THREAD_METADATA.json
https://github.com/discord/discord-api-docs/commit/53ee0109b874bde5ec2316379bf266bb332630a0
> Support for thread timestamps

- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestGuildScheduledEventAPI.cs
- Backend/Remora.Discord.Rest/API/GuildScheduledEvents/DiscordRestGuildScheduledEventAPI.cs
- Tests/Remora.Discord.Rest.Tests/API/GuildScheduledEvents/DiscordRestGuildScheduledEventAPITests.cs
https://github.com/discord/discord-api-docs/pull/4380
> Support for Guild Scheduled Event cover-images

- Remora.Discord.Extensions/Builder/BuilderBase.cs
- Remora.Discord.Extensions/Errors/ValidationError.cs
> Add attachment uri scheme to BuilderBase

- Remora.Discord.Extensions/Embeds/EmbedBuilder.cs
> Set EmbedBuilder default color to null

- .idea/.idea.Remora.Discord/.idea/misc.xml
- Remora.Discord.sln
- Samples/Modals/ModalCommand.cs
- Samples/Modals/ModalReceiver.cs
- Samples/Modals/Modals.csproj
- Samples/Modals/Program.cs
Just a simple sample to provide an idea to people, how to respond to a command with a modal and how to extract the information the user responded with.
> Adding a Sample for Modals

- Backend/Remora.Discord.Gateway/Extensions/ServiceCollectionExtensions.cs
Adds the ability to configure the rest client from extension method that adds the gateway client.
> feat: Configure rest client from gateway extension method

- Backend/Remora.Discord.API.Abstractions/API/Gateway/Events/Invites/IInviteDelete.cs
- Backend/Remora.Discord.Caching.Abstractions/Services/ICacheProvider.cs
- Backend/Remora.Discord.Caching.Redis/Services/RedisCacheProvider.cs
- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
- Remora.Discord.Extensions/Remora.Discord.Extensions.csproj
- Tests/Remora.Discord.Gateway.Tests/Transport/Events/SendExceptionEvent.cs
PR fixes some minor typos in Remora.Discord.Extension project description and typos in function documentation.
> Fix minor typos

- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestGuildAPI.cs
- Backend/Remora.Discord.Rest/API/Guilds/DiscordRestGuildAPI.cs
- Tests/Remora.Discord.Rest.Tests/API/Guild/DiscordRestGuildAPITests.cs
See https://github.com/discord/discord-api-docs/pull/5219
> Change DeleteMessageDays to DeleteMessageSeconds

- Backend/Remora.Discord.Rest/Utility/ImagePacker.cs
ImagePacker.PackImageAsync creates a new `byte[]` out of the Stream even if a MemoryStream is passed; if the input stream is not a MemoryStream, it allocates *two* byte arrays with the size of the image being uploaded.
This PR fixes this by using TryGetBuffer if the underlying Stream is a MemoryBuffer and allows it, falling back to ToArray otherwise. When the Stream has to be copied to a buffer, we also retrieve the MemoryStream's underlying buffer instead of allocating a new one.
> Improve memory pressure in ImagePacker by not allocating extra byte[] buffers if they can be retrieved from the Stream directly

- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
Set variables before starting the ReceiverTask
#252
> Fix hanging tests

- .github/workflows/dotnet.yml
Install required .NET 7 SDK in CI aswell.
- CI build
> Install .NET 7 in CI

- Backend/Remora.Discord.API.Abstractions/API/Gateway/Events/ConnectingResuming/IReady.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Activities/IActivityButton.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Messages/IAttachment.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Messages/IEmbedImage.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Messages/IEmbedThumbnail.cs
- Backend/Remora.Discord.API/API/Gateway/Events/ConnectingResuming/Ready.cs
- Backend/Remora.Discord.API/API/Objects/Activities/ActivityButton.cs
- Backend/Remora.Discord.API/API/Objects/Messages/Attachment.cs
- Backend/Remora.Discord.API/API/Objects/Messages/EmbedImage.cs
- Backend/Remora.Discord.API/API/Objects/Messages/EmbedThumbnail.cs
- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
- Remora.Discord.Extensions/Builder/BuilderBase.cs
- Remora.Discord.Extensions/Embeds/EmbedAuthorBuilder.cs
- Remora.Discord.Extensions/Embeds/EmbedBuilder.cs
- Remora.Discord.Extensions/Embeds/EmbedFooterBuilder.cs
- Remora.Discord.Extensions/Embeds/EmbedImageBuilder.cs
- Remora.Discord.Extensions/Formatting/Markdown.cs
Adds UriStringAttribute annotations (from ReSharper.Annotations) to URI string properties, fields and parameters in source code.
> Add UriString markers

- .config/dotnet-tools.json
- docfx/docfx_project/articles/intro.md
- docfx/docfx_project/docfx.json
Tested. Also adds xrefService, which fixes references to C# types (like Int64)
Currently looking into adding docs to Remora.Rest, Remora.Commands, etc.
> Update DocFX  to newest version.

- Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs
- Remora.Discord.Commands/Feedback/Services/FeedbackService.cs
- Remora.Discord.Commands/Feedback/Services/IFeedbackService.cs
This PR implements an higher abstraction level for FeedbackService, it will allow people to mock FeedbackService easier.
> feat: implement abstraction level for feedback service

- Backend/Remora.Discord.Rest/API/Webhooks/DiscordRestWebhookAPI.cs
https://github.com/discord/discord-api-docs/pull/5999
> Webhook name "discord" is not allowed

- Backend/Remora.Discord.API.Abstractions/Results/DiscordError.cs
https://github.com/discord/discord-api-docs/pull/5948
> Add new error code

- Backend/Remora.Discord.API.Abstractions/API/Objects/Guilds/IGuildOnboarding.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Guilds/IOnboardingPrompt.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Guilds/IPromptOption.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Guilds/PromptType.cs
- Backend/Remora.Discord.API.Abstractions/API/Rest/IDiscordRestGuildAPI.cs
- Backend/Remora.Discord.API/API/Objects/Guilds/GuildOnboarding.cs
- Backend/Remora.Discord.API/API/Objects/Guilds/OnboardingPrompt.cs
- Backend/Remora.Discord.API/API/Objects/Guilds/PromptOption.cs
- Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs
- Backend/Remora.Discord.Caching/API/CachingDiscordRestGuildAPI.cs
- Backend/Remora.Discord.Caching/KeyHelpers.cs
- Backend/Remora.Discord.Rest/API/Guilds/DiscordRestGuildAPI.cs
- Tests/Remora.Discord.API.Tests/API/Objects/Guilds/GuildOnboardingTests.cs
- Tests/Remora.Discord.API.Tests/API/Objects/Guilds/OnboardingPromptTests.cs
- Tests/Remora.Discord.API.Tests/API/Objects/Guilds/PromptOptionTests.cs
- Tests/Remora.Discord.Rest.Tests/API/Guild/DiscordRestGuildAPITests.cs
- Tests/Remora.Discord.Tests/Samples/Objects/GUILD_ONBOARDING/GUILD_ONBOARDING.json
- Tests/Remora.Discord.Tests/Samples/Objects/ONBOARDING_PROMPT/ONBOARDING_PROMPT.json
- Tests/Remora.Discord.Tests/Samples/Objects/PROMPT_OPTION/PROMPT_OPTION.json
- Tests/Remora.Discord.Tests/Samples/Objects/PROMPT_OPTION/PROMPT_OPTION.nulls.json
Implements https://github.com/discord/discord-api-docs/pull/5915
> Implement onboarding

- Backend/Remora.Discord.API.Abstractions/API/Objects/Permissions/DiscordPermission.cs
- Backend/Remora.Discord.API.Abstractions/API/Objects/Permissions/DiscordVoicePermission.cs
https://github.com/discord/discord-api-docs/pull/6017
> Add new permissions

- Remora.Discord.Pagination/Interactions/PaginationInteractions.cs
> Allow only the source user to paginate through message

- Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs
- Backend/Remora.Discord.Gateway/Transport/IPayloadTransportService.cs
- Backend/Remora.Discord.Gateway/Transport/WebSocketPayloadTransportService.cs
- Tests/Remora.Discord.Gateway.Tests/Transport/MockedTransportService.cs
This PR adds even further optimizations to receiving and particularly sending payloads.
This is in addition to #300.
> Optimize the websocket (again)

- Samples/LoadRespondersFromAssembly/LoadRespondersFromAssembly.csproj
- Samples/LoadRespondersFromAssembly/Program.cs
There should be a sample to demonstrate `LoadCommandGroupsFromAssembly` as well, but I don't know how to implement it best.
> Use Remora.Discord.Extensions method in LoadRespondersFromAssembly
